"""
Django settings for hello_world project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/topics/settings/
"""

import os
from pathlib import Path
from decouple import config


# Admin безпека
ADMIN_URL = os.environ.get('DJANGO_ADMIN_URL', 'admin/')

# URLs
ROOT_URLCONF = 'project_portfolio.urls'




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True)



# Читаємо ALLOWED_HOSTS з environment variable
DJANGO_ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if DJANGO_ALLOWED_HOSTS:
    ALLOWED_HOSTS = [host.strip() for host in DJANGO_ALLOWED_HOSTS.split(',')]
else:
    # Fallback для Azure
    ALLOWED_HOSTS = [
        'django-app-budget-1752082786.azurewebsites.net',
        '.azurewebsites.net',
        'localhost',
        '127.0.0.1'
    ]




if 'CODESPACE_NAME' in os.environ:
    codespace_name = config("CODESPACE_NAME")
    codespace_domain = config("GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN")
    CSRF_TRUSTED_ORIGINS = [f'https://{codespace_name}-8000.{codespace_domain}']

# Application definition


# Переконайтеся, що admin app включений
INSTALLED_APPS = [
    'django.contrib.admin',          # ✅ Admin панель
    'django.contrib.auth',           # ✅ Аутентифікація
    'django.contrib.contenttypes',   # ✅ Content types
    'django.contrib.sessions',       # ✅ Сесії
    'django.contrib.messages',       # ✅ Повідомлення
    'django.contrib.staticfiles',    # ✅ Статичні файли
    # Ваші додатки
]

#INSTALLED_APPS = [
#    "django.contrib.admin",
#    "django.contrib.auth",
#    "django.contrib.contenttypes",
#    "django.contrib.sessions",
#    "django.contrib.messages",
#   "django.contrib.staticfiles",
#    "django_browser_reload",
#]


# Middleware для admin
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # ✅ Для admin сесій
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # ✅ Для admin auth
    'django.contrib.messages.middleware.MessageMiddleware',     # ✅ Для admin messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]



X_FRAME_OPTIONS = "ALLOW-FROM preview.app.github.dev"

ROOT_URLCONF = "project_portfolio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "project_portfolio" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project_portfolio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "project_portfolio" / "static",
]

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "project_portfolio" / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "project_portfolio" / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
