"""
Django settings for project_portfolio project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/topics/settings/
"""

import os
import logging
from pathlib import Path
from functools import lru_cache

# Azure Key Vault imports
try:
    from azure.keyvault.secrets import SecretClient
    from azure.identity import DefaultAzureCredential, ClientSecretCredential
    AZURE_AVAILABLE = True
except ImportError:
    AZURE_AVAILABLE = False
    logging.warning("Azure SDK not installed. Falling back to environment variables.")

# Legacy support for decouple (можна видалити пізніше)
try:
    from decouple import config
    DECOUPLE_AVAILABLE = True
except ImportError:
    DECOUPLE_AVAILABLE = False
    # Fallback функція
    def config(key, default=None, cast=None):
        value = os.environ.get(key, default)
        if cast and value is not None:
            return cast(value)
        return value

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Logger configuration
logger = logging.getLogger(__name__)

# Environment detection
def detect_environment():
    """Визначає середовище виконання"""
    if os.environ.get('CODESPACES') or os.environ.get('CODESPACE_NAME'):
        return 'codespace'
    elif os.environ.get('GITHUB_ACTIONS'):
        return 'github_actions'
    elif os.environ.get('WEBSITE_SITE_NAME'):  # Azure App Service
        return 'azure_app_service'
    elif os.environ.get('DYNO'):  # Heroku
        return 'heroku'
    else:
        return 'local'

RUNTIME_ENVIRONMENT = detect_environment()
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'dev')

# Key Vault configuration
KEY_VAULT_URL = os.environ.get('KEY_VAULT_URL', 'https://django-app-dev-kv.vault.azure.net/')

logger.info(f"Runtime environment: {RUNTIME_ENVIRONMENT}")
logger.info(f"Application environment: {ENVIRONMENT}")

def get_azure_credential():
    """Отримує Azure credentials залежно від середовища"""
    if RUNTIME_ENVIRONMENT == 'codespace':
        # У Codespace використовуємо Service Principal
        client_id = os.environ.get('AZURE_CLIENT_ID')
        client_secret = os.environ.get('AZURE_CLIENT_SECRET')
        tenant_id = os.environ.get('AZURE_TENANT_ID')
        
        if all([client_id, client_secret, tenant_id]):
            logger.info("Using Service Principal authentication for Codespace")
            return ClientSecretCredential(
                tenant_id=tenant_id,
                client_id=client_id,
                client_secret=client_secret
            )
        else:
            logger.warning("Service Principal credentials not found in Codespace")
            return None
    
    elif RUNTIME_ENVIRONMENT == 'azure_app_service':
        # В Azure App Service використовуємо Managed Identity
        logger.info("Using Managed Identity authentication")
        return DefaultAzureCredential()
    
    elif RUNTIME_ENVIRONMENT == 'local':
        # Локально використовуємо Azure CLI
        logger.info("Using DefaultAzureCredential for local development")
        return DefaultAzureCredential()
    
    else:
        logger.warning(f"No Azure authentication for environment: {RUNTIME_ENVIRONMENT}")
        return None

@lru_cache(maxsize=128)
def get_secret(secret_name, default=None):
    """
    Отримує секрет з різних джерел залежно від середовища
    
    Пріоритет:
    1. Environment variables (для Codespace/CI)
    2. Azure Key Vault (для Azure/production)
    3. Default value
    """
    # Для Codespace та інших CI/CD середовищ - спочатку environment variables
    if RUNTIME_ENVIRONMENT in ['codespace', 'github_actions']:
        env_variations = [
            secret_name.upper().replace('-', '_'),  # DATABASE_PASSWORD
            f"KV_{secret_name.upper().replace('-', '_')}",  # KV_DATABASE_PASSWORD
            secret_name.replace('-', '_'),  # database_password
            secret_name.upper(),  # DATABASE-PASSWORD
        ]
        
        for env_key in env_variations:
            env_value = os.environ.get(env_key)
            if env_value:
                logger.debug(f"Using environment variable {env_key} for {secret_name}")
                return env_value
    
    # Якщо Azure SDK недоступний
    if not AZURE_AVAILABLE:
        logger.warning(f"Azure SDK unavailable, using default for {secret_name}")
        return default
    
    # Спробуємо Key Vault
    credential = get_azure_credential()
    if not credential:
        logger.warning(f"No Azure credentials, using default for {secret_name}")
        return default
    
    try:
        client = SecretClient(vault_url=KEY_VAULT_URL, credential=credential)
        secret = client.get_secret(secret_name)
        logger.debug(f"Retrieved secret {secret_name} from Key Vault")
        return secret.value
        
    except Exception as e:
        logger.error(f"Error retrieving secret {secret_name} from Key Vault: {e}")
        return default

# Legacy функція для сумісності
def get_secret_legacy(secret_name):
    """Legacy функція для сумісності з існуючим кодом"""
    try:
        return get_secret(secret_name)
    except Exception as e:
        print(f"Помилка отримання секрету {secret_name}: {e}")
        return None

# =============================================================================
# CORE DJANGO SETTINGS
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret('django-secret-key', 'dev-secret-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
if RUNTIME_ENVIRONMENT == 'codespace':
    DEBUG = True  # Завжди True в Codespace
else:
    DEBUG = get_secret(f'django-debug-{ENVIRONMENT}', 'true').lower() == 'true'

# Allowed hosts configuration
def get_allowed_hosts():
    """Конфігурує ALLOWED_HOSTS залежно від середовища"""
    
    # Отримуємо з Key Vault або environment
    kv_allowed_hosts = get_secret('django-allowed-hosts')
    env_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS')
    
    allowed_hosts = []
    
    if kv_allowed_hosts:
        allowed_hosts.extend([host.strip() for host in kv_allowed_hosts.split(',')])
    elif env_allowed_hosts:
        allowed_hosts.extend([host.strip() for host in env_allowed_hosts.split(',')])
    
    # Додаємо специфічні хости для кожного середовища
    if RUNTIME_ENVIRONMENT == 'codespace':
        allowed_hosts.extend([
            'localhost',
            '127.0.0.1',
            '0.0.0.0',
            '.githubpreview.dev',
            '.github.dev',
            '.app.github.dev',
            '*',  # У dev середовищі дозволяємо все
        ])
    elif RUNTIME_ENVIRONMENT == 'azure_app_service':
        # Azure App Service хости
        site_name = os.environ.get('WEBSITE_SITE_NAME')
        if site_name:
            allowed_hosts.extend([
                f'{site_name}.azurewebsites.net',
                '.azurewebsites.net',
            ])
    
    # Базові хости для всіх середовищ
    allowed_hosts.extend([
        'django-app-budget-1752082786.azurewebsites.net',
        '.azurewebsites.net',
        'localhost',
        '127.0.0.1'
    ])
    
    # Видаляємо дублікати та пусті значення
    return list(filter(None, set(allowed_hosts)))

ALLOWED_HOSTS = get_allowed_hosts()

# CSRF trusted origins для Codespace
CSRF_TRUSTED_ORIGINS = []
if RUNTIME_ENVIRONMENT == 'codespace':
    codespace_name = os.environ.get("CODESPACE_NAME")
    codespace_domain = os.environ.get("GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN")
    if codespace_name and codespace_domain:
        CSRF_TRUSTED_ORIGINS = [f'https://{codespace_name}-8000.{codespace_domain}']

# X-Frame options для GitHub preview
X_FRAME_OPTIONS = "ALLOW-FROM preview.app.github.dev"

# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Додаємо browser reload тільки в development
if DEBUG and RUNTIME_ENVIRONMENT in ['codespace', 'local']:
    try:
        import django_browser_reload
        INSTALLED_APPS.append('django_browser_reload')
    except ImportError:
        pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Додаємо browser reload middleware тільки в development
if DEBUG and 'django_browser_reload' in INSTALLED_APPS:
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')

ROOT_URLCONF = 'project_portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'project_portfolio' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_portfolio.wsgi.application'

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================

def get_codespace_database_config():
    """PostgreSQL конфігурація для Codespace"""
    codespace_configs = [
        {
            'host': os.environ.get('POSTGRES_HOST', 'localhost'),
            'port': os.environ.get('POSTGRES_PORT', '5432'),
            'name': os.environ.get('POSTGRES_DB', 'postgres'),
            'user': os.environ.get('POSTGRES_USER', 'postgres'),
            'password': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        },
        {
            'host': 'db',
            'port': '5432',
            'name': 'project_portfolio',
            'user': 'django_user',
            'password': 'django_password',
        },
    ]
    
    for config in codespace_configs:
        if config['password']:
            logger.info(f"Using Codespace PostgreSQL: {config['host']}:{config['port']}")
            return {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': config['name'],
                    'USER': config['user'],
                    'PASSWORD': config['password'],
                    'HOST': config['host'],
                    'PORT': config['port'],
                    'OPTIONS': {
                        'sslmode': 'disable',
                        'connect_timeout': 10,
                    },
                }
            }
    return None

def get_database_config():
    """Повна конфігурація бази даних"""
    
    # Для Codespace
    if RUNTIME_ENVIRONMENT == 'codespace':
        codespace_db = get_codespace_database_config()
        if codespace_db:
            return codespace_db
    
    # Key Vault секрети
    db_password = get_secret('database-password') or get_secret('postgres-password')
    postgres_host = get_secret('postgres-host')
    postgres_database = get_secret('postgres-database', f'django_{ENVIRONMENT}')
    postgres_username = get_secret('postgres-username', 'dbadmin')
    postgres_port = get_secret('postgres-port', '5432')
    
    # Environment variables (legacy)
    db_password = db_password or os.environ.get('DB_PASSWORD')
    postgres_host = postgres_host or os.environ.get('DB_HOST', 'localhost')
    postgres_database = postgres_database or os.environ.get('DB_NAME', 'django-app_db')
    postgres_username = postgres_username or os.environ.get('DB_USER', 'djangoadmin')
    postgres_port = postgres_port or os.environ.get('DB_PORT', '5432')
    
    # DATABASE_URL має найвищий пріоритет
    database_url = get_secret('database-url') or os.environ.get('DATABASE_URL')
    if database_url:
        try:
            import dj_database_url
            config = dj_database_url.parse(database_url)
            if ENVIRONMENT in ['staging', 'prod', 'production']:
                config['OPTIONS'] = {'sslmode': 'require'}
            logger.info("Using database configuration from DATABASE_URL")
            return {'default': config}
        except ImportError:
            logger.warning("dj-database-url not installed")
    
    # PostgreSQL конфігурація
    if db_password and postgres_host:
        logger.info("Using PostgreSQL configuration")
        ssl_mode = 'require' if ENVIRONMENT in ['staging', 'prod', 'production'] else 'prefer'
        
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': postgres_database,
                'USER': postgres_username,
                'PASSWORD': db_password,
                'HOST': postgres_host,
                'PORT': postgres_port,
                'OPTIONS': {
                    'sslmode': ssl_mode,
                    'connect_timeout': 60,
                },
                'CONN_MAX_AGE': 600,
                'CONN_HEALTH_CHECKS': True,
            }
        }
    
    # Fallback до SQLite
    logger.warning("No database credentials found, using SQLite")
    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

DATABASES = get_database_config()

# =============================================================================
# CACHE CONFIGURATION
# =============================================================================

def get_cache_config():
    """Конфігурація кешу"""
    if RUNTIME_ENVIRONMENT == 'codespace':
        return {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'codespace-cache',
            }
        }
    
    redis_url = get_secret('redis-url')
    redis_password = get_secret('redis-password')
    
    if redis_url:
        redis_config = {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": redis_url,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                }
            }
        }
        
        if redis_password:
            redis_config["default"]["OPTIONS"]["PASSWORD"] = redis_password
        
        return redis_config
    
    return {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

CACHES = get_cache_config()

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================

def get_email_config():
    """Конфігурація email"""
    if RUNTIME_ENVIRONMENT == 'codespace' or DEBUG:
        return {
            'EMAIL_BACKEND': 'django.core.mail.backends.console.EmailBackend',
        }
    
    return {
        'EMAIL_HOST': get_secret('email-host', 'localhost'),
        'EMAIL_PORT': int(get_secret('email-port', '25')),
        'EMAIL_HOST_USER': get_secret('email-host-user', ''),
        'EMAIL_HOST_PASSWORD': get_secret('email-host-password', ''),
        'EMAIL_USE_TLS': True,
        'DEFAULT_FROM_EMAIL': get_secret('default-from-email', 'noreply@example.com'),
    }

# Застосовуємо email конфігурацію
email_settings = get_email_config()
for key, value in email_settings.items():
    globals()[key] = value

# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# Session configuration
SESSION_COOKIE_AGE = int(get_secret('session-cookie-age', '1209600'))  # 2 weeks
SESSION_COOKIE_NAME = get_secret('session-cookie-name', f'sessionid_{ENVIRONMENT}')

# Security settings для production
if ENVIRONMENT in ['staging', 'prod', 'production']:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =============================================================================
# STATIC & MEDIA FILES
# =============================================================================

STATICFILES_DIRS = [
    BASE_DIR / 'project_portfolio' / 'static',
]

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'project_portfolio' / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'project_portfolio' / 'media'

# Azure Storage configuration (якщо потрібно)
azure_storage_account = get_secret('azure-storage-account-name')
azure_storage_key = get_secret('azure-storage-account-key')

if azure_storage_account and azure_storage_key and ENVIRONMENT in ['staging', 'prod']:
    DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
    STATICFILES_STORAGE = 'storages.backends.azure_storage.AzureStorage'
    
    AZURE_ACCOUNT_NAME = azure_storage_account
    AZURE_ACCOUNT_KEY = azure_storage_key
    AZURE_CONTAINER = get_secret('azure-storage-container-media', 'media')
    AZURE_CUSTOM_DOMAIN = f'{azure_storage_account}.blob.core.windows.net'

# =============================================================================
# DEFAULT SETTINGS
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        __name__: {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}

# =============================================================================
# FINAL LOGGING
# =============================================================================

# Логування конфігурації
logger.info(f"Database engine: {DATABASES['default']['ENGINE']}")
logger.info(f"Database host: {DATABASES['default'].get('HOST', 'SQLite')}")
logger.info(f"Runtime environment: {RUNTIME_ENVIRONMENT}")
logger.info(f"Debug mode: {DEBUG}")
logger.info(f"Allowed hosts: {len(ALLOWED_HOSTS)} hosts configured")
logger.info(f"Cache backend: {CACHES['default']['BACKEND']}")

# Спеціальне повідомлення для Codespace
if RUNTIME_ENVIRONMENT == 'codespace':
    logger.info("🚀 Running in GitHub Codespace environment")
    logger.info("📝 Using development-friendly settings")
    if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
        logger.info("💾 Using SQLite database")
    else:
        logger.info("🐘 Using PostgreSQL database")

# Validation критичних налаштувань
if not SECRET_KEY or SECRET_KEY == 'dev-secret-key-change-in-production':
    if ENVIRONMENT in ['prod', 'production']:
        raise ValueError("SECRET_KEY must be set for production!")
    else:
        logger.warning("Using default SECRET_KEY in development")

